name: Code Quality 🧹

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v2

      - name: Setup Node.js 🟩
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "20"
      - name: Install Dependencies 📥
        run: pnpm install

      - name: Build 🏗
        run: pnpm build -- --no-pack

      - name: Lint 🧹
        run: pnpm lint
