name: Build and Release 🏗

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - /:/host
    permissions:
      contents: write

    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v4

      - name: Update pacman 📦
        run: pacman -Sy --noconfirm gnome-shell-extensions gettext nodejs pnpm

      - name: Install Dependencies 📥
        run: pnpm install

      - name: Build 🏗
        run: pnpm build

      - name: Release 🚀
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
